server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docs4dev?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
weixin:
  mp:
    security:
      # APPID
      appid: wxee8e8890484d1fe3
      # APP secret
      secret: 2461e7108c79de08d690b1b532fa71c4
      # 微信后台配置的 token
      token: 1234567890
      # 微信后台配置的消息加解密 aeskey
      encodingAesKey: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG
